### ISSUE TITLE
Positional Argument 

### ISSUE THREAD

**Issue by SylvainGuieu** [mpkocher/pydantic-cli#30]
Hello, 
I really like the tool and it is almost what I was looking for. I say almost because of this : 

> Limitations
> 
> - Positional Arguments are not supported. This created too much friction with the JSON file loading feature which could turn positional required arguments into optional values which fundamentally could changed the commandline interface.

For me this make the package unusable. Is there any workaround ?

**Comment by mpkocher** [comment]
There are two core features of pydantic-cli:

- Define and validate models using Pydantic and use these schemas as an interface to the command line
- Load partial or complete models using JSON (these are essentially, partial or complete config or "preset" files)

Positional arguments create friction points when combined with loading model values from a JSON file. More specifically, (required) positional values of the model could be supplied in the JSON and are no longer required at the command line. 

For example:

```python
from pydantic import BaseModel
from pydantic_cli import run_and_exit, to_runner, DefaultConfig

class MinOptions(BaseModel):
    class Config(DefaultConfig):
        CLI_JSON_ENABLE = True
    
    input_file: str
    input_hdf: str
    max_records: int = 100
```

And the vanilla case running from the command line works as expected.

```bash
my-tool /path/to/file.txt /path/to/file.h5 --max_records 200
```

However, when using the JSON "preset" feature, there are potential problems where the positional arguments of the tool are shifting around depending on what fields have been defined in the JSON preset.

For example, running with this `preset.json`, the `input_file` positional argument is no longer required. 

```json
{"input_file": "/system/config.txt", "max_records": 12345}"
```

Vanilla case works as expected.

```bash
my-tool  file.txt /path/to/file.h5 --json-config ./preset.json
```

But this also works

```bash
my-tool  /path/to/file.h5 --json-config ./preset.json
```

In my experience, **the changing of the semantic meaning of the command line tool's positional arguments depending on the contents of the `preset.json` created issues and bugs**.

The simplest fix is to remove the positional arguments in favor of `-i` or similar which removed the issue.

```python
from pydantic import BaseModel
from pydantic_cli import run_and_exit, to_runner, DefaultConfig

class MinOptions(BaseModel):
    class Config(DefaultConfig):
        CLI_JSON_ENABLE = True
        CLI_EXTRA_OPTIONS = {'input_file': ('-i, '), 'input_hdf: ('-d', '--hdf'), 'max_records': ('-m', '--max-records')}
    
    input_file: str
    input_hdf: str
    max_records: int = 100
```

Running with the `preset.json` defined above, works as expected.

```bash
my-tool --hdf /path/to/file.h5 --json-config ./preset.json
```

As well as overriding the `-i`. 

```bash
my-tool -i file.txt --hdf /path/to/file.h5 --json-config ./preset.json
```

This consistency was the motivation for removing positional argument support in earlier versions of `pydantic-cli`. 

Here's an "incomplete" list of other libraries that might be a better fit for your requirements.

https://github.com/mpkocher/pydantic-cli#other-related-tools

**Comment by mpkocher** [comment]
I've updated the docs to try to better express the reasons why positional args are not supported. 

https://github.com/mpkocher/pydantic-cli#why-are-positional-arguments-not-supported

Thanks for the comments and feedback.
