### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by mariusvniekerk** [mpkocher/pydantic-cli#46]
Can we have a release with the MANIFEST changes?  Presently they is blocking packaging it on conda-forge https://github.com/conda-forge/staged-recipes/pull/16390

**Comment by mpkocher** [comment]
The Manifest.in file should now be included in 4.2.1.

- https://github.com/mpkocher/pydantic-cli/releases/tag/v4.2.1
- https://pypi.org/project/pydantic-cli/
